create table
  public.budgets (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    user_id bigint null,
    budget_amount numeric null,
    category_id bigint null,
    start_date date null,
    end_date date null,
    period_type_id bigint null,
    constraint budget_categories_pkey primary key (id),
    constraint budget_categories_category_id_fkey foreign key (category_id) references categories (id),
    constraint budgets_category_id_fkey foreign key (category_id) references categories (id),
    constraint budgets_period_type_id_fkey foreign key (period_type_id) references period_types (id),
    constraint budgets_user_id_fkey foreign key (user_id) references users (id)
  ) tablespace pg_default;

create table
  public.categories (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    name text null,
    constraint categories_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.period_types (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default timezone ('utc'::text, now()),
    name text not null,
    period interval not null,
    constraint table_name_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.tags (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    user_id bigint not null,
    name text null,
    constraint tags_pkey primary key (id),
    constraint tags_user_id_fkey foreign key (user_id) references users (id)
  ) tablespace pg_default;

create table
  public.transactions (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    user_id bigint null,
    category_id bigint null,
    transaction_date date null,
    place text null,
    amount numeric null,
    tag_id bigint null,
    note text null,
    constraint transactions_pkey primary key (id),
    constraint transactions_category_id_fkey foreign key (category_id) references categories (id),
    constraint transactions_tag_id_fkey foreign key (tag_id) references tags (id),
    constraint transactions_user_id_fkey foreign key (user_id) references users (id)
  ) tablespace pg_default;

create table
  public.users (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    password_hash text null,
    password_salt text null,
    username text null,
    constraint users_pkey primary key (id)
  ) tablespace pg_default;
